language: bash
os:
  - osx
python:
  - "2.7"
env:
  global:
    - pkgdir="/Volumes/Python 2.7.3/Python.mpkg/Contents/Packages"
    - wheelhouse="https://s3-us-west-1.amazonaws.com/typea-wheelhouse/index.html"
before_install:
  - wget http://www.python.org/ftp/python/2.7.3/python-2.7.3-macosx10.6.dmg
  - hdiutil mount python-2.7.3-macosx10.6.dmg
  - sudo installer -package "$pkgdir/PythonFramework-2.7.pkg"
    -target "/" -allowUntrusted -dumplog
  - sudo installer -package "$pkgdir/PythonUnixTools-2.7.pkg"
    -target "/" -allowUntrusted -dumplog
  - sudo installer -package "$pkgdir/PythonProfileChanges-2.7.pkg"
    -target "/" -allowUntrusted -dumplog
  - pip install mkwheelhouse
install:
  - for req in $(grep -h '^[^- ]' requirements.txt requirements_darwin.txt);
    do pip install --find-links "$wheelhouse" --no-index "$req" ||
    mkwheelhouse "$wheelhouse" "$req";
    done
script:
  - pip install --find-links "$wheelhouse" --no-index -r requirements_darwin.txt
