language: bash
os:
  - osx
python:
  - "2.7"
env:
  global:
    - PYTHON_HOME="/Library/Frameworks/Python.framework/Versions/2.7"
    - PIP="${PYTHON_HOME}/bin/pip"
    - MACOSX_DEPLOYMENT_TARGET="10.6"
    - pkgdir="/Volumes/Python 2.7.3/Python.mpkg/Contents/Packages"
    - bucket="typea-wheelhouse"
    - wheelhouse="https://s3-us-west-1.amazonaws.com/typea-wheelhouse/index.html"
    - AWS_ACCESS_KEY_ID="AKIAJOCYHVNQQKP3BN3A"
    - secure: "OuzbvcAKTyc6qv9FzGC7oO6z5KYErT79vHRgUFtvvWNxGd6cQKwITKJ4DW3IsNtjDXI5a+1ZeWD9LJHSmy3O73img4y3OnMpHhYrhWK3oFgIswilZYl+B8oSV3h1Pj1wurFJ+1u4Wy908YQEE9guknVWXMeIWglt6STLiJ2KPys="
before_install:
  - wget http://www.python.org/ftp/python/2.7.3/python-2.7.3-macosx10.6.dmg
  - hdiutil mount python-2.7.3-macosx10.6.dmg
  - sudo installer -package "$pkgdir/PythonFramework-2.7.pkg"
    -target "/" -allowUntrusted -dumplog
  - sudo installer -package "$pkgdir/PythonUnixTools-2.7.pkg"
    -target "/" -allowUntrusted -dumplog
  - sudo installer -package "$pkgdir/PythonProfileChanges-2.7.pkg"
    -target "/" -allowUntrusted -dumplog
  - sudo $PIP install
     virtualenv
install:
  - virtualenv wheelenv && source wheelenv/bin/activate
  - $PIP install mkwheelhouse
  # Install or create cached wheels on s3.
  - for req in $(grep -h '^[^- ]' requirements.txt requirements_darwin.txt);
    do $PIP install --find-links "$wheelhouse" --no-index "$req" ||
    mkwheelhouse "$bucket" "$req";
    done
  - deactivate
script:
  - virtualenv testenv && source testenv/bin/activate
  - $PIP install --find-links "$wheelhouse" --no-index -r requirements_darwin.txt
